### ISSUE TITLE
saving OpenLayers map results in looping of "Retrieving layers".

### ISSUE THREAD

**Issue by mstuyts** [tomchadwin/web2qgis#13]
When I try to save an OpenLayers map, it detects it correct, but when I click Save, the Python Console shows a loop of the message "Retrieving layers".

![web2qgis_retrieving layers](https://user-images.githubusercontent.com/11028014/40104330-539c4cf4-58f0-11e8-936b-4409e6c553df.jpg)

I tested it with multiple maps, like for example https://openlayers.org/en/latest/examples/simple.html.

**Comment by tomchadwin** [comment]
Only the import has been coded so far, so Save doesn't yet work.

**Comment by tomchadwin** [comment]
Test against master. Thanks!
