### ISSUE TITLE
Intermittent failure to import detected map

### ISSUE THREAD

**Issue by tomchadwin** [tomchadwin/web2qgis#2]
Suspect this could be an async issue: need to await `evaluateJavaScript()` result (no idea how yet).

**Comment by tomchadwin** [comment]
Detecting the map seems to work fine, but I'm having problems with detecting the extent. I think I need to separate out the import from the detect. I'll try connecting import to the Save button.

**Comment by tomchadwin** [comment]
Detect and import now separate, and things do seem to have improved. Will leave open for a bit, awaiting feedback.

**Comment by hareldunn** [comment]
This [url](http://www.hamaarag.org.il/ajax/unit-polygons) is detected, but crashes repeatedly on 'save', throwing 
`AttributeError: 'NoneType' object has no attribute 'split'`
![image](https://user-images.githubusercontent.com/24369355/40083062-be0a9a1e-589b-11e8-8b8e-e24d553e59fe.png)

**Comment by tomchadwin** [comment]
I thought that issue had called down a bit. It's only where it tries to import the view (ie the extent). For the moment, I'll wrap it in a`try:` until we can figure out what the underlying fault is.

**Comment by tomchadwin** [comment]
As far as I can tell, this is *not* an async issue. The problem arises when the JS executed gives an error, or in any way doesn't give the expected output. I'll close this issue for now, and will open more specific ones as appropriate.
