### ISSUE TITLE
long url

### ISSUE THREAD

**Issue by mstuyts** [tomchadwin/web2qgis#3]
If the url of the webpage is very long only a part of the url is visible in the start screen. Maybe the input box clould grow with the length of the url, or it could be larger (vertical and/or horizontal) so the full url is visible.

![web2qgis_long_url](https://user-images.githubusercontent.com/11028014/40047105-df560b30-582e-11e8-81ab-b0ffa27d407f.jpg)

**Comment by tomchadwin** [comment]
I'd argue that is normal GUI behaviour. A solution might be to have the field expand when you expand the window (not sure how to do that yet).

**Comment by mstuyts** [comment]
And if you make the field multiline, 3 or 4 lines high with a vertical scroll bar from the start, regardless of the length of the url? The window has some empty space you can use.

**Comment by tomchadwin** [comment]
I'm not sure. I fee as though a text input for a URL *should* be one line...

**Comment by tomchadwin** [comment]
I've committed a change so that it stays on one line - it should not have been multiline. Hope it's an improvement.

**Comment by mstuyts** [comment]
That's much better. I still prefer multi line fields for long texts, but that's a personal preference. 

With the QLineEdit object I now get an error message, but for that I'll file a separate bug report.

**Comment by tomchadwin** [comment]
Thanks for the feedback. I can be persuaded to change my mind about multiline, but I think single line is the right choice at the moment. My guess is that the majority of users will simply copy and paste from their browser address bar.
